-- =====================================================
-- MIGRATION 002: Roles (Admin/Mod/User) + Admin Panel
-- Schema: fogueteiros
-- =====================================================
-- NOTA: A tabela perfis com a constraint cargo_check
-- já foi criada na migration create_perfis_table.
-- Este arquivo é mantido apenas como referência.
--
-- Promover um usuário a admin (rodar com o UUID alvo):
-- UPDATE perfis SET cargo = 'admin' WHERE id = 'SEU_UUID_AQUI';
--
-- Verificar:
-- SELECT id, nome, cargo FROM perfis;
